### ISSUE TITLE
Error in Windows7

### ISSUE THREAD

**Issue by kuangyunsheng** [jaredallard/nexe#125]
My envirement: 
    windows 7, vs 2013, python 2.7, node.js 0.12.7

I write a simple js file:

    console.log('hello');

D:\dev\test\node.js\hello>nexe -i hello.js -o hello.exe
----> framework => nodejs
----> bundle D:\dev\test\node.js\hello\hello.js
----> bundle -> D:\dev\test\node.js\hello\tmp\nexe\nodejs\latest\node-v0.12.7\li
b\nexe.js
----> embedResources undefined
----> resource -> D:\dev\test\node.js\hello\tmp\nexe\nodejs\latest\node-v0.12.7\
lib\nexeres.js
----> vcbuild [make stage]
'python' 
Failed to create vc project files.
----> cp D:\dev\test\node.js\hello\tmp\nexe\nodejs\latest\node-v0.12.7\Release\n
ode.exe D:\dev\test\node.js\hello\hello.exe
----> copied

D:\dev\test\node.js\hello>hello
>

**Comment by jaredallard** [comment]
Hello! Try using the `--python` flag to point to the location of python.

**Comment by jaredallard** [comment]
Please let me know if this solved it for you! Until then, closing!
