### ISSUE TITLE
Using prebuilt binary of node.js?

### ISSUE THREAD

**Issue by davidhesselbom** [jaredallard/nexe#127]
Hi!

I'm making a simple application in typescript. I tried nexe for the first time today, and I was disappointed to find that building my application took as long as it did (over 5 minutes), which, as I understand it, is because nexe also compiles node.js, which is pretty complex in itself. I'm very new to all this, but assuming it's not possible to compile only the parts of node.js I actually need for my application, is it possible to make nexe use an existing binary of node.js (for example, one of the binaries available for download at the node.js website) instead of building the whole thing from scratch?

I apologize in advance for not knowing enough about all this to realize this kind of question is dumb, if that's the case.

**Comment by jaredallard** [comment]
Unfortunately-- no. The way this is built, well, it depends on the compilation. However, you can modify code and rebuild it with very little build time! So, really, it's only the first time that takes a bit of time.

I highly recommend against using nexe when developing, but more for when it's being released. :smile:

**Comment by davidhesselbom** [comment]
Alright, I understand. I'll have to find some way to cache things between builds. Thanks!

**Comment by jaredallard** [comment]
I'll see what I can do about making it take less time :)
