### ISSUE TITLE
Can't find 'nexe.js' after packaged in run.

### ISSUE THREAD

**Issue by wcc21320** [jaredallard/nexe#128]
I'm using ubuntu 14.04 and have installed nexe in global and build command is: `nexe -i app.js -o bin/rc -r 0.10.31`. I packaged my app to 'bin/rc'. But it run with below error dump; Would you please help to guide me what's the issue?

```js
$  bin/rc

module.js:340
    throw err;
          ^
Error: Cannot find module 'nexe.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at nexe.js:31:90
    at Array.call./home/wcc/run_test/IT/node_modules/aplan-rados-client/client.js.net [as 0] (nexe.js:247:20)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.call./home/wcc/run_test/IT/ITcli.js.fs [as 0] (nexe.js:58:14)
    at initModule (nexe.js:29:11)
```

**Comment by jaredallard** [comment]
Greetings. Will look into this. Probably something to do with the monkey patching. That aspect of nexe needs love right now, it's been having issues with the latest node version & a hacky implementation of supporting them by me.

**Comment by jaredallard** [comment]
I can't seem to reproduce this. Can you give me some idea of what your `bin/rc` code is?

**Comment by wcc21320** [comment]
It seems about to require my another module: 'aplan-rados-client'
my app.js
//-----------------------------------------------------
'use strict';

var fs = require('fs');
var client = require('aplan-rados-client');

function checkServer(callback){
    client.init(conf.server, function(err, inf){
        if (inf && inf.result) {
            return callback(null, inf.result);
        } else {
            logError('radosClient init failed:', err);
            return callback(2);
        }
    });
}

checkServer(function(err, conn){
    if (err) {
        console.log('Can not contact to radosServer.');
    } else {
        console.log('radosServer ready!');
    }
});
//-----------------------------------------------------
and 'aplan-rados-client' locate at node_modules, and it is many exports functions (call to dnode) with file head as:

//-----------------------------------------------------
/**
 * Client.js
 **/
'use strict';

// ---------- Include Modules ----------


var dnode = require('dnode');
function newDnode(){
    return dnode(undefined, {weak:false});
}

var net = require('net');
var clientmodule = require(__filename);
// ---------- Variables ----------

var aplan_rados_server = {
    host: '192.168.22.3',
    port: 5004
};

exports.enableLog = function(enable, enableError){
    if (false === enable || true === enable)
        log_enable = enable;

    if (false === enableError || true === enableError)
        log_enableError = enableError;


    return log_enable;
};

var log_enable;// = true;//
var log_enableError;
// ---------- Functions ----------

And the module: 'dnode' is from  "http://github.com/substack/dnode.git"

**Comment by jaredallard** [comment]
Alright! Will look into this soon :smile:

**Comment by wcc21320** [comment]
Thanks for your quick reply. 
I wonder if below statement will be the cause?
:     var clientmodule = require(__filename);

**Comment by jaredallard** [comment]
OH. We don't don't support dynamic requires. Yes, that would be it!

**Comment by jaredallard** [comment]
I quote the readme:

Doesn't support dynamic require statements

Such As:

var x = require(someVar);

In this case nexe won't bundle the file

    var x;
    if (someCheck) {
        x = require("./ver1.js");
    } else {
        x = require("./var2.js");
    }

In this case nexe will bundle both files.

Workarounds: 1) for dynamic requires that you want bundled add the following into your project

    var dummyToForceIncludeForBundle = false;
    if (dummyToForceIncludeForBundle) {
        require("./loadedDynamicallyLater.js");
        // ...
    }

this will trick the bundler into including them.

2) for dynamic files getting included that you don't want to be

    var moduleName = "./ver2.js";
    if (someCheck) {
        moduleName = "./ver1.js";
    }
    var x = require(moduleName);

Note: neither file will be bundled.

Using these two techniques you can change your application code so modules are not bundles, and generate a includes.js file as part of your build process so that the right files get bundled for your build configuration.

**Comment by jaredallard** [comment]
`__filename` becomes nexe.js

**Comment by wcc21320** [comment]
thank you, I will try the workaround.

**Comment by jaredallard** [comment]
Let me know how it goes!

**Comment by wcc21320** [comment]
After I remove dynamic require statements, it still work in command "node app.js"; but after I build it in nexe, it block at
nexe.js:105
    d.connect({host:aplan_rados_server.host, port: aplan_rados_server.port}, f
      ^
TypeError: Object #<Object> has no method 'connect'
    at Object.exports.init (nexe.js:105:7)
    at checkServer (nexe.js:56:12)
    at Array.call./home/wcc/run_test/IT/app.js.fs [as 0] (nexe.js:66:1)
    at initModule (nexe.js:29:11)
    at Array.forEach (native)
    at nexe.js:39:8
    at nexe.js:46:4
    at NativeModule.compile (node.js:900:5)
    at Function.NativeModule.require (node.js:869:18)
    at Function.Module._load (module.js:297:25)

I simple the project as below:
app.js:
//--------------------------------------------------------
var client = require('aplan-rados-client');
var conf = {'ver':'0.1',
        'server':{host:'192.168.22.3',port:6004}
    };
function checkServer(callback){
    client.init(conf.server, function(err, inf){
        if (inf ) {
            return callback(null, inf.result);
        } else {
            console.log('radosClient init failed:', err);
            return callback(2);
        }
    });
}

checkServer(function(err, conn){
    if (err) {
        console.log('Can not contact to radosServer.');
    } else {
        console.log('radosServer ready!');
    }
});
//--------------------------------------------------------
and 'aplan-rados-client' has its app.js:
//--------------------------------------------------------
var dnode = require('dnode');
function newDnode(){
    return dnode(undefined, {weak:false});
}

var net = require('net');
// ---------- Variables ----------
var aplan_rados_server = {
    host: '192.168.22.3',
    port: 5004
};
// ---------- Export Functions ----------
exports.init = function (options, callback) {

    if (options.host) aplan_rados_server.host = options.host;
    if (options.port) aplan_rados_server.port = options.port;

    // check server alive:
    var d = newDnode();
    d.connect({host:aplan_rados_server.host, port: aplan_rados_server.port}, function(remote, conn){
        console.log('connected to server:', options);

        remote._ping(function (s) {
            console.log('Server say: ', s);
            callback(null, {message:'successed'});
            conn.end();
        });
    }).on('error', function(e){
        console.log(e);
        callback(1,{message:e.message});
    });
};
//--------------------------------------------------------
And the module: 'dnode' is from "http://github.com/substack/dnode.git"
It seems not recognize donde object correctly.
