### ISSUE TITLE
parameters are being sent to node.js instead of my application

### ISSUE THREAD

**Issue by wcc21320** [jaredallard/nexe#129]
I build a simple program 'ss'; but my parameter "-w" will be treated as for node-js. How should I do?

$ bin/ss -w
Error: unrecognized flag -w
Try --help for options

Commands:
    -w: Write a file to ceph. -w folder/filename -f full_file_path_name
    -r: Read a file from ceph. -r folder/filename -f full_file_path_name
    -l: List files of a folder. -l folder
    -d: Delete a file in ceph. -d folder/filename

**Comment by jaredallard** [comment]
Hi! What's your cli opts looking like for invoking `nexe`?

Also, to clarify, are you saying that node.js is interpreting your flags instead of your program?

**Comment by jaredallard** [comment]
Try compiling with `-f true` in your `nexe` opts. i.e

```
nexe -i ./app.js -o ./out -f true -F iojs -r 3.0.0
```

**Comment by wcc21320** [comment]
with -f true is work! Thanks!
