### ISSUE TITLE
use browserify to bundle files

### ISSUE THREAD

**Issue by jaredallard** [jaredallard/nexe#131]
Currently, it would seem, that browserify doesn't have half the problems that nexe does with combining everything into one file. This is essentially what nexe does, then it's added as the `nexe` module in node sources, and then from there everything works.

I propose using browserify to generate the files, I'm going to start a browserify branch with these improvements. However, I'd like some feedback on this as it is a major change! Usage should **not** be affected.

**Comment by jaredallard** [comment]
So far browserify fixes many issues, but it cannot build nexe at the moment. I've been working on solving this.

**Comment by divmgl** [comment]
Why about using something like System.js? Would you like me to help with this?

**Comment by jaredallard** [comment]
@divmgl I'm open for any suggestions :)

**Comment by divmgl** [comment]
@jaredallard going to fork and try today

**Comment by jaredallard** [comment]
@divmgl Let me know if you run into any issues!

**Comment by divmgl** [comment]
Unfortunately, System.js builder will not be a good choice for this as you would need to create complex config files to tell System.js where to find packages you need to require. I can look into fixing the browserify issues if you'd like.

**Comment by jaredallard** [comment]
Any help is welcome! Been having issues myself, the branch for this is `browserify` if you want to take a look. However it's not the setup, at the moment, it's a few isolated issues with browserify. It currently will *not* build itself.



Date: Fri, 23 Oct 2015 15:13:18 -0700

**Comment by jaredallard** [comment]
Using!
