### ISSUE TITLE
Suppress console

### ISSUE THREAD

**Issue by 1j01** [jaredallard/nexe#133]
I'd like to prevent the command line window from opening, as I'm opening my own window with an [nw.js](https://github.com/nwjs/nw.js/) application that I'm extracting from an nexe resource. I can close the console pretty quickly because I exit right after launching the application but it would be nice to be able to hide it entirely.

**Comment by jaredallard** [comment]
Not sure this is exactly handled by nexe. You'd have to have something else executing it in the foreground. With windows you could potentially run it with something like `cmd /c <exe>` (using `child_process`.exec) but that's of the top of my head. Let me know if you come across anything so I can add your solution to the README, or feel free to PR what you did later on.

Thanks :)

**Comment by 1j01** [comment]
Well, the `exe` is supposed to be my final distributable for a game I'm making, so people will be launching it directly.

I tried modifying `node_main.cc` to use `WinMain` and after much fiddling with types (gotta love having a million different incompatible types of strings) eventually got it to give me an [error](http://stackoverflow.com/questions/7410798/c-fatal-error-lnk1120-1-unresolved-externals) where the accepted answer is "you made the wrong choice of application type". I also tried modifying `common.gypi`, adding `"Subsystem": 2"` and that didn't work, although in retrospect there are places in there that explicitly specify the subsystem as "Console".

Then today I tried modifying the exe directly and eventually got that to work with this python script (`pe.py`):

```python
#!/usr/bin/python
# based on http://stackoverflow.com/a/14806704/2624876

import sys
import struct

if len(sys.argv) < 2:
	print "Parameter required: exe file to modify"
	sys.exit(-1)

exe = open(sys.argv[1], "r+b")
exe.seek(0x3c)
(PeHeaderOffset,) = struct.unpack("<H", exe.read(2))

exe.seek(PeHeaderOffset)
(PeSignature,) = struct.unpack("<I", exe.read(4))
if PeSignature != 0x4550:
	print "File is missing PE header signature"

exe.seek(PeHeaderOffset + 0x5C)
# Specify GUI mode
exe.write(struct.pack("<H", 0x02))
# Console mode would be 0x03

exe.close()

print "Completed succesfully."

```
Spawning this with:
```coffee
{spawn} = require "child_process"

py = spawn "python.exe", ["pe.py", game_exe]
py.on "error", (err)->
	throw err
output = ""
py.stderr.on "data", (data)->
	output += data
py.stdout.on "data", (data)->
	output += data
py.on "close", (exit_code)->
	if exit_code is 0
		console.log "Done"
	else
		console.error "Python exited with code #{exit_code}:\n#{output}"
```

**Comment by 1j01** [comment]
Rewritten in CoffeeScript using [bufferpack](https://github.com/ryanrolds/bufferpack):

```coffee
fs = require "fs"
struct = require "bufferpack"

module.exports = (exe_path, subsystem="gui")->
	exe = fs.openSync exe_path, "r+"
	
	read = (position, length)->
		buffer = new Buffer length
		fs.readSync exe, buffer, 0, length, position
		buffer
	
	write = (position, buffer)->
		fs.writeSync exe, buffer, 0, buffer.length, position
	
	[PeHeaderOffset] = struct.unpack "<H", read 0x3c, 2
	[PeSignature] = struct.unpack "<I", read PeHeaderOffset, 4
	
	if PeSignature isnt 0x4550
		throw new Error "File is missing PE header signature"
	
	subsystem_value = switch subsystem.toLowerCase()
		when "console" then 3
		when "gui", "windows" then 2
	
	console.log "Current subsystem value:", (struct.unpack "<H", read PeHeaderOffset + 0x5C, 2)[0]
	write PeHeaderOffset + 0x5C, struct.pack "<H", [subsystem_value]
	console.log "New subsystem value:", (struct.unpack "<H", read PeHeaderOffset + 0x5C, 2)[0]
	
	fs.close exe
	console.log "Completed succesfully."
```

**Comment by ayapi** [comment]
@1j01 Hi, your .coffee was a great help! It works well. Thank you very much.

**Comment by ayapi** [comment]
i noticed, after overwriting Subsystem, maybe we cant use stdout unfortunately ;(
so i gave up and added few patch to wmain() in node_main.cc
`ShowWindow( GetConsoleWindow(), SW_HIDE );`

found discussion nodejs/node#556 "Silent Mode execution"

**Comment by 1j01** [comment]
@ayapi Did your patch work? I'm now running into two problems relating to my hacking of the subsystem: when my program is "installing" (downloading and extracting nw.js when running for the first time), there's no indication that anything is happening (it can take a while to download), and it exits immediately when run as a screensaver (whereas it works when the subsystem is `console`, albeit with a console)
So, does `ShowWindow( GetConsoleWindow(), SW_HIDE );` hide it before it's visible?
Also, would it be possible for the program to show the console through some API?

**Comment by ayapi** [comment]
> So, does ShowWindow( GetConsoleWindow(), SW_HIDE ); hide it before it's visible?

unfortunately, my patch isn't perfect either.
it hides console window immediately, but it hides **after** visible, not **before**.
so, console window appears in a split second :(

> Also, would it be possible for the program to show the console through some API?

i wonder if i can.. but i have no knowledge and idea :(

**Comment by drahgon55** [comment]
@1j01 and @ayapi, I do not know if you guys are still having this issue, but I wrote a program a while ago that solved it using the shellExecute function. Here is a snippit from my c++ program

t1is the path to the exe and t2 are the parameters your passing

    string t1 = "\"";
    t1 += argv[1];
    t1 += "\"";

    string t2 = "\"";
    t2 += argv[2];
    t2 += "\"";

    HINSTANCE hInst = ShellExecute(NULL, "open", t1.c_str(), t2.c_str(), NULL, SW_HIDE);

Also here is a link to the documentation:
https://msdn.microsoft.com/en-us/library/windows/desktop/bb762153(v=vs.85).aspx

hope that helps

**Comment by 1j01** [comment]
@drahgon55 The thing is, I can't use a wrapper* for my use case. The user will be launching the exe directly (i.e. through Windows Explorer).

*The exe is a sort of wrapper, but that's not important. I don't have control over how it's launched.

**Comment by drahgon55** [comment]
@1j01 Ahh yes I did miss the part where it was getting launched directly. My solution will not work then.

You mentioned that you need it completely invisible, it seems your script above which sets the gui type to application does that. You then mentioned that you do not see a window during install and that became an issue. 

Is it that you need to show it during install and hide the window when it is done. Doing this all in Javascript?

**Comment by 1j01** [comment]
@drahgon55 Yeah, that's what I want ideally.

**Comment by drahgon55** [comment]
@1j01 well ktrzeciaknubisa from jxcore project was able to do this. He has a video showing it in action here is a link to the issues thread. It is the 6th reply down. 
https://github.com/jxcore/jxcore/issues/159

It seems he created hooks from javascript to the c++ code. Doing this he was able to call ShowWindow api directly. Might be worth talking to him about it.

**Comment by drahgon55** [comment]
@1j01 Also no idea if this would work. But it might be possible to run your nexe app normally in console mode, show install process and when the install is done launch another instance of the app from within the app using childprocess(this is the part I'm not sure if is possible) module and this time suppressing the console. Then the first instance of the app exits leaving only the console suppressed version running

**Comment by 1j01** [comment]
@drahgon55 It shouldn't show the console briefly when it's launched after having been installed though, so it would need to be a non-console app that ideally would create and show a console for the install process the first time.

**Comment by jaredallard** [comment]
Closing this as it isn't an issue with nexe! Feel free to continue any conversation.

**Comment by bittu** [comment]
Can anyone help to achieve same with mac executable?
