### ISSUE TITLE
Handle build failure

### ISSUE THREAD

**Issue by 1j01** [jaredallard/nexe#134]
The first three or four times I tried to build with nexe it failed for some reason with this error:
```
----> cp C:\Users\My\Projects\hacky-game\temp\nodejs\latest\node-v0.12.7\Release\node.exe ./game.exe
....> ERROR: Couldn't copy binary.

C:\Users\My\Projects\hacky-game\node_modules\nexe\lib\exe.js:236
                                        throw err; // dump raw error object
                                              ^
Error: ENOENT, lstat 'C:\Users\My\Projects\hacky-game\temp\nodejs\latest\node-v0.12.7\Release\node.exe'
```
*(Afterwards it worked except when trying to include massive resources in the exe...)*

I don't *think* I saw any errors above (just warnings), but there may have been. I'd like to suggest adding a check for the file's existence with a more descriptive error like "`The release binary ('C:\Users\My\Projects\hacky-game\temp\nodejs\latest\node-v0.12.7\Release\node.exe') has not been generated. This indicates a failure in the build process. There may be additional information above.`" (sort of like what npm says, that last bit, except there's definitely "additional logging output above")

If the file has already been created and the build fails, the error can go by silently, pass unnoticed and lead to confusion. Because of this, the release binary should be deleted when starting building. There's probably a clean script, but you don't *need* to clean everything and it may be easier just to delete the file.

**Comment by 1j01** [comment]
I can probably make a PR for these changes.

**Comment by jaredallard** [comment]
First off; resources hasn't been very battle-hardened or stress tested, so it could very well have some limits. Second off, I always welcome a PR even if I could easily do it! Makes my life easier, and it allows other people to contribute!

Lastly, yes that almost always indicates a build failure. I never saw it as an issue as I was the one who developed that aspect so to me I knew what that meant immediately. I'm all for better output.

**Comment by 1j01** [comment]
I was able to work around the limits of the resources (which tend to come up as python `MemoryError`s) by including only a zip of my nw.js app and using parts of nw-builder to download the nw.js runtime at runtime. So it's pretty good although I'd love to be able to have it work offline if better resource support is implemented (i.e. not generating source code like it tries to.)

And yeah, it's obviously failing to build, it's more just that it's distracting from the root cause.
