### ISSUE TITLE
Unrecognized commanderjs CLI options

### ISSUE THREAD

**Issue by fbiville** [jaredallard/nexe#135]
I just tested the latest stable version of `nexe` against a tiny CLI-configurable HTTP server (commander: 2.8.1, express: 4.13.3).

I cannot specify any command line parameters to the generated binary. Any known workaround or fix for this?

**Comment by jaredallard** [comment]
Hi! Have you tried adding `-f true` to your command line with nexe?

That's normally the cause, this enables command line opts being passed to the node.js script instead of node.

**Comment by fbiville** [comment]
Nice, it works perfectly! Thanks a lot!
