### ISSUE TITLE
TypeError: require(...) is not a function on require("./streams")(iconv);

### ISSUE THREAD

**Issue by computerwizjared** [jaredallard/nexe#137]
I'm probably missing something big here, but to compile the executable on Windows I run the command:
```nexe -i ./bin/www -o ./run.exe```

When I try to run the executable, I get this error:
```
nexe.js:24231
        require("./streams")(iconv);
                            ^
TypeError: require(...) is not a function
    at Array.__dirname.call.C:\Users\compu\IdeaProjects\Project\node_modules
\body-parser\node_modules\iconv-lite\lib\index.js../extend-node (nexe.js:24231:2
9)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.__dirname.call.C:\Users\compu\IdeaProjects\Project\node_modules
\body-parser\node_modules\raw-body\index.js.unpipe (nexe.js:28503:13)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.__dirname.call.C:\Users\compu\IdeaProjects\Project\node_modules
\body-parser\lib\read.js.zlib (nexe.js:23930:15)
    at initModule (nexe.js:29:11)
    at nexe.js:31:64
    at Array.__dirname.call.C:\Users\compu\IdeaProjects\Project\node_modules
\body-parser\lib\types\json.js.http-errors (nexe.js:375:12)
```

This is a simple app created in Express and EJS.
Am I doing something obviously wrong, and if not how would I fix this? Thanks!

**Comment by jaredallard** [comment]
Thanks for submitting this. Could you try the browserify branch? Also, please post some source so I can try to reproduce this. Thanks!

**Comment by computerwizjared** [comment]
I'm now getting this error after re-compiling the executable, on the master branch.

```
fs.js:251
        0
        ^

SyntaxError: missing ) after argument list
    at runInThisContext (node.js:860:18)
    at NativeModule.compile (node.js:944:14)
    at NativeModule.require (node.js:893:18)
    at module.js:8:12
    at NativeModule.compile (node.js:945:5)
    at Function.NativeModule.require (node.js:893:18)
    at evalScript (node.js:540:31)
    at startup (node.js:91:9)
    at node.js:954:3
```

I would try the browserify branch but I can't figure out how to run nexe outside of it's node directory when using the cloned repository. Here's a link to the code that produces this error: https://www.dropbox.com/s/p40ms6ljcp2qr86/DebugExpress1.zip?dl=0

**Comment by jaredallard** [comment]
Will try to look into this when I can, unfortunately work is taking my time right now.

**Comment by computerwizjared** [comment]
That's fine, I was just curious and thought this project looked cool. I understand completely :smiley:

**Comment by jaredallard** [comment]
Look like I can check this out on thursday. Don't hesitate to ping me on Twitter (@jaredallard) about it as well, since I noticed you have one. (It's the best way to get me to remember to do stuff :Smile:)

**Comment by jaredallard** [comment]
With browserify it compiles, buuttttt nothing happens.

**Comment by computerwizjared** [comment]
You must run ```npm start``` which I believe runs ```node bin/www```

**Comment by jaredallard** [comment]
@computerwizjared That would be it, whoops! Haven't used a style like that for awhile!

**Comment by computerwizjared** [comment]
Hm, thanks. I forgot to mention that it does compile on the master branch, and that this is a runtime error.

**Comment by jaredallard** [comment]
Yea, I figured as much, I'll spend more time on this tomorrow. (Work calls for tonight!)

**Comment by jaredallard** [comment]
This is fixed in `nexe@1`. I have personally tested it with your code with the params:

```bash
npm install
sudo npm install -g nexe
nexe -i bin/www -r 5.5.0 -t src app
```

**Comment by computerwizjared** [comment]
Awesome, thanks! I'll be able to test it tonight, and will get back to you.

**Comment by computerwizjared** [comment]
Thanks so much! It works now :+1:
