### ISSUE TITLE
Failed to locate VS2015 after installation

### ISSUE THREAD

**Issue by ebudianto** [jaredallard/nexe#138]
Hi, 

As mentioned in the readme, I have to install VS2010+ in order to run nexe on Windows and I did that by installing VS2015. However, when running the nexe command I'm still faced with the same following errors on my NodeJS command prompt:

----> vcbuild [make stage]
Looking for Visual Studio 2015
Looking for Visual Studio 2013
Failed to find Visual Studio installation.

What would be the main cause for this problem?

**Comment by jaredallard** [comment]
Hi! This isn't handled by nexe. This is handled by node.js (I presume you're using 4.1+) Can you build regular node?

**Comment by szmokus** [comment]
I have the same issue. I tried installing VS2015, VS2010 and VS2013 but none of it helped.
Any suggestion?
(I'm using Windows 10)

**Comment by jaredallard** [comment]
I can't reproduce on W8.1

Can't access 10 at the moment, but I'd take this up with node.js

**Comment by computerwizjared** [comment]
I am running Windows 10 x64 and node.js found Visual Studio 2015 Community fine. Ensure that you have ran Visual Studio at least once (although I know that you probably have already). Otherwise, I can't reproduce.

**Comment by szmokus** [comment]
I installed only the VS2013 after removed all VS from my system and now it works perfectly. I have no idea what was wrong at first.
Nice product! Keep up the good work! ;)

**Comment by jaredallard** [comment]
Glad this was resolved! Feel free to report any other issue you have! I try to work on this project when I can :)

**Comment by mark-archer** [comment]
I got this same error with VS2015, had to open VS -> new project -> install visual c++ tools

**Comment by noXi89** [comment]
@mark-archer same here, thank you.

**Comment by CleristonBernardes** [comment]
@mark-archer thanks for the solution, I just wonder how did you find it.

**Comment by mark-archer** [comment]
I forget.  I think I just assumed based on the error that it needed the c++ compiler but couldn't find it and then I assumed that could be gotten by installing the c++ tools.  Glad it's helping other people.

**Comment by PineAppleInNCU** [comment]
@mark-archer 

it works!!!!!!thanks you a lot
