### ISSUE TITLE
After build failure, nexe continues on to copying an executable into place. 

### ISSUE THREAD

**Issue by deployable** [jaredallard/nexe#146]
```
----> vcbuild [make stage]
'python' is not recognized as an internal or external command,
operable program or batch file.
Cannot determine current version of Node.js
----> cp C:\node\node-client\tmp\nodejs\4.2.1\node-v4.2.1\
Release\node.exe ./client.exe
----> copied
```

**Comment by jaredallard** [comment]
Whoops :P 

This isn't supposed to happen :(

**Comment by migottojf** [comment]
You should add C:\Python27; to the environment variables. https://code.google.com/p/tryton/wiki/AddingPythonToWindowsPath

**Comment by jaredallard** [comment]
Oh, so using it by default?

**Comment by jaredallard** [comment]
Closing because I believe this was fixed quite a few commits ago

**Comment by deployable** [comment]
@migottojf the bug was the copying of the binary after the failure due to the missing python path, not the missing python path itself. 

@jaredallard cheers
