### ISSUE TITLE
Incompatible with js-yaml

### ISSUE THREAD

**Issue by amiorin** [jaredallard/nexe#148]
```
----> framework => nodejs
----> bundle /Users/...
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received { buffer: false }
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at /usr/local/lib/node_modules/nexe/node_modules/resolve/lib/async.js:151:37
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

nexe: 0.4.2 and d6a43f8ddb0d6e398360c5c288937aff594226fb
node: v5.0.0

**Comment by jaredallard** [comment]
Argh. Will have to look into this. Any reproducible code? (I can create one myself but it would save me time)

**Comment by amiorin** [comment]
https://gist.github.com/amiorin/1f4648f4d4ab77e0907f

**Comment by blazekas** [comment]
I had the same issue with Express:

var express = require('express');
var app = express();

app.get('/', function (req, res) {
  res.send('Hello World')
});

Error is because methods/package.json (used by express) or js-yaml/package.json
has "browser" property of type object like -

"browser": {
    "buffer": false
  }

I think this situation should be handled in nexe/lib/bundle.js

**Comment by jaredallard** [comment]
@blazekas This is a known issue. Due to module-deps. I think a PR was made to fix it on their side, I will look into that.

**Comment by jaredallard** [comment]
Issue is with node.js and resolve at the moment I fear. Try using node 4.x.x

**Comment by jaredallard** [comment]
Try `nexe@1.0.0`

**Comment by jaredallard** [comment]
Confirmed working with `nexe@1.0.6`!

**Comment by megastef** [comment]
I've got a similar issue with the "rc" module with ode 6.1.0: 
```
./spm-agent-nginx.bin 
nexe.js:51491
    throw new Error('rc(name): name *must* be string')
    ^
```

https://github.com/dominictarr/rc/blob/master/index.js#L13

RC checks the type of the parameter, which should be a string (and there is normally no problem ...):
https://github.com/sematext/spm-agent/blob/master/lib/util/spmconfig.js#L51
