### ISSUE TITLE
require-js/dojo AMD modules?

### ISSUE THREAD

**Issue by gbaumgart** [jaredallard/nexe#151]
hi,
most of my code works both ways, client & server, thanks to require-js/dojo = AMD 

However, any idea how I can get my modules included in builds ? 
thanks

**Comment by jaredallard** [comment]
More information please?

**Comment by gbaumgart** [comment]
hi, thanks for the heads up! I m talking about AMD applications which use something like this:

```js
require([
    "dojo/_base/declare",
    "dojo/_base/lang",
    "xcf/driver/DriverBase",
    "dojo/node!commander"
], function(declare,lang,DriverBase,commander)
{ ...do something with this modules....});

It looks your parser can only grab this single require("mid") calls, but not an array. I tried all day long all sorts of things, but it never worked. Also in AMD applications, its not 'require' but 'define'.

nexe seems to be the only choice and I have to tweak it now. Do you by chance where in your code you're grabbing require calls? I somehow hope I can 'hack' for AMD requires; ( i have still no glue how you add these files to the exe..)

close this simply if its out of your reach.

**Comment by gbaumgart** [comment]
does it make more sense to you now ? at the end i really would love to know only where you grab those require calls, i was looking through all your sources but i can't see it ;-)

**Comment by gbaumgart** [comment]
however, the code to get dynamic modules, and also support for require-js apps is already written somewhere here :https://github.com/dojo/util
sorry, thats all i can say.
