### ISSUE TITLE
couldn't find require 'fsevents', errors may occur.

### ISSUE THREAD

**Issue by MartinMuzatko** [jaredallard/nexe#153]
Hello there!
I tried nexe via node CLI and I got the following errors.
```
C:\Users\Martin\Desktop\test>nexe -i app.js
----> framework => nodejs
----> bundle C:\Users\Martin\Desktop\test\app.js
....> WARNING: couldn't find require 'fsevents', errors may occur.
path.js:146
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.win32.resolve (path.js:146:13)
    at C:\Users\Martin\AppData\Roaming\npm\node_modules\nexe\node_modul
es\browser-resolve\node_modules\resolve\lib\async.js:151:37
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Is this something NEXE related or is it the fault of the code that I want to nexify?

Thanks in advance.

**Comment by MartinMuzatko** [comment]
Update: fsevents is required by some code (chokidar), but is unsupported for Windows.

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.5
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

I guess there is nothing you can do about this.

**Comment by jaredallard** [comment]
This is a issue with node 5.x.x right now. Try using 4.x.x or below.

**Comment by MartinMuzatko** [comment]
Alright! Thank you a lot.
