### ISSUE TITLE
Debug support

### ISSUE THREAD

**Issue by trekkor-jas** [jaredallard/nexe#155]
Is there a way to debug a compiled executable? 

If I set options.flags = false and use the --debug-brk=<port> flag to enable debugging, the application crashes during the startup (nexe module not found). 

It seems that when debugging is enabled, the application runs on an isolated environment where the bundled nexe module is not available.

**Comment by jaredallard** [comment]
Debug is currently not supported, and I haven't looked into it.

**Comment by jaredallard** [comment]
Closing as it's a feature that is currently not planned to be developed! Thanks for the input and support! :)
