### ISSUE TITLE
Rasbian support?

### ISSUE THREAD

**Issue by basssolo** [jaredallard/nexe#156]
I'm really noobie on this but I was trying to use nexe on Rasbian OS in my Raspberry PI. I could not make it compile the node and my node.js application. This works fine with my Mac OS X. I tried with many node versions. Currently v4.0.0 is running successfully on my PI but it won't compile with Nexe. Should this work or maybe I'm missing something?

**Comment by jaredallard** [comment]
Hi! Can you provide a log so I can help you out with this? Thanks :)

**Comment by basssolo** [comment]
Jared thanks for your reply. Obviously I should have slept over night and checked everything again. Turns out it was outdated compiler on Raspberry and I was overlooking the log warning, because it was not error :) Thanks again, I got it working now as expected.

**Comment by jaredallard** [comment]
@basssolo Let me know if you have any other issues! :)
