### ISSUE TITLE
Support simultaneous build jobs

### ISSUE THREAD

**Issue by issacg** [jaredallard/nexe#159]
It would be great if we could take advantage of `make -j xx` or `msbuild /MP[xx]` to speed up node.js builds!

**Comment by jaredallard** [comment]
If you know of a way to make node.js compilation by itself to do so, let me know
and I can implement this easily!


On Sat, Dec 26, 2015 at 1:49 PM, Issac < notifications@github.com [notifications@github.com] > wrote:
It would be great if we could take advantage of make -j xx or msbuild /MP[xx] to speed up node.js builds!

**Comment by issacg** [comment]
It took me a while to get Windows building, but it seems Windows is already doing it.  I'll look into this on Linux next time I do a build (this time I just stopped the build after "make" started, and manually ran make -j <num_cpu_cores> which worked fine for the initial compile

**Comment by issacg** [comment]
#147 deals with Linux

**Comment by issacg** [comment]
(it would be helpful if you published 0.4.3 :))

**Comment by jaredallard** [comment]
Will do asap.
