### ISSUE TITLE
build fails if input file is not index.js

### ISSUE THREAD

**Issue by drahgon55** [jaredallard/nexe#161]
I am using nexe with package.json configuration. If I change the input file to something other than index.js I get a build failure. Here is my failing nexe config in my package.json. Just changing input to index.js makes it work for me

```
"nexe": {
    "input": "drive.js",
    "output": "nexe^$",
    "temp": "src",
    "runtime": {
      "framework": "nodejs",
      "version": "4.2.4",
      "ignoreFlags": true
    }
  }
```

**Comment by jaredallard** [comment]
Hi! Please provide the failure output?

**Comment by jaredallard** [comment]
Please re-open when you have the following!
