### ISSUE TITLE
version 1.0.4 errors when packaging 'express-test'

### ISSUE THREAD

**Issue by ptmoy2** [jaredallard/nexe#165]
pm@T110:~/Projects/express/express-test$ nexe -v
```
1.0.4
```
pm@T110:~/Projects/express/express-test$ nexe -i index.js -o out

```
----> framework => nodejs
----> downloading https://nodejs.org/dist/node-latest.tar.gz
[==============================================================================]
----> tar -xf /home/pm/Projects/express/express-test/tmp/nexe/nodejs/latest/nodejs-latest.tar.gz -C /home/pm/Projects/express/express-test/tmp/nexe/nodejs/latest
----> bundle /home/pm/Projects/express/express-test/index.js
----> Browserify finished
----> embedResources undefined
----> resource -> /home/pm/Projects/express/express-test/tmp/nexe/nodejs/latest/node-v5.5.0/lib/nexeres.js
----> monkey patch /home/pm/Projects/express/express-test/tmp/nexe/nodejs/latest/node-v5.5.0/node.gyp
----> monkey patch /home/pm/Projects/express/express-test/tmp/nexe/nodejs/latest/node-v5.5.0/src/node.js
----> monkey patch /home/pm/Projects/express/express-test/tmp/nexe/nodejs/latest/node-v5.5.0/lib/child_process.js
----> make
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./configure ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by jaredallard** [comment]
Try git, or 1.0.5 if its out.

On Mon, Jan 25, 2016 at 4:51 PM, ptmoy2 < notifications@github.com [notifications@github.com] > wrote:
pm@T110:~/Projects/express/express-test$ nexe -v

104


pm@T110:~/Projects/express/express-test$ nexe -i indexjs -o out

----> framework => nodejs
----> downloading https://nodejsorg/dist/node-latesttargz
[==============================================================================]
----> tar -xf /home/pm/Projects/express/express-test/tmp/nexe/nodejs/latest/nodejs-latesttargz -C /home/pm/Projects/express/express-test/tmp/nexe/nodejs/latest
----> bundle /home/pm/Projects/express/express-test/indexjs
----> Browserify finished
----> embedResources undefined
----> resource -> /home/pm/Projects/express/express-test/tmp/nexe/nodejs/latest/node-v550/lib/nexeresjs
----> monkey patch /home/pm/Projects/express/express-test/tmp/nexe/nodejs/latest/node-v550/nodegyp
----> monkey patch /home/pm/Projects/express/express-test/tmp/nexe/nodejs/latest/node-v550/src/nodejs
----> monkey patch /home/pm/Projects/express/express-test/tmp/nexe/nodejs/latest/node-v550/lib/child_processjs
----> make
eventsjs:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /configure ENOENT
    at exports_errnoException (utiljs:874:11)
    at ProcessChildProcess_handleonexit (internal/child_processjs:178:32)
    at onErrorNT (internal/child_processjs:344:16)
    at doNTCallback2 (nodejs:441:9)
    at process_tickCallback (nodejs:355:17)

**Comment by jaredallard** [comment]
See #167.
