### ISSUE TITLE
Cannot find module browserify

### ISSUE THREAD

**Issue by reverentgeek** [jaredallard/nexe#170]
Builds were working find with 0.4.2 (I think that was the version I had before). I upgraded to 1.0.5, and now I'm getting the following:

```
----> framework => nodejs
----> bundle /Users/david/Projects/leankit/leankit-data-utility-cli/tmp/src/index.js
module.js:328
    throw err;
    ^

Error: Cannot find module '/Users/david/Projects/leankit/leankit-data-utility-cli/node_modules/nexe/node_modules/browserify/bin/cmd.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3

....> ERROR: Browserify failed to launch
```

Thanks,
David

**Comment by jaredallard** [comment]
Hi! Platform and the full command line?

**Comment by reverentgeek** [comment]
I'm on Mac OS X El Capitan. I've got a Windows 10 VM, but haven't tried it there yet. I've got a gulp task that runs nexe. I reverted back to 0.4.2, and it works fine.  Below is the gulp task. `output: buildDir.path(filename)` is equivalent to `output: "./build/leankit-data-utility"`.

```
gulp.task( "compile", [ "copy-task", "docs" ], ( callback ) => {
	let filename = "leankit-data-utility";
	if ( currentOs() === "windows" ) {
		filename += ".exe";
	}

	let options = {
		input: tmpDir.path( "src/index.js" ),
		output: buildDir.path( filename ),
		python: "python",
		nodeTempDir: "./tmp",
		nodeVersion: "latest",
		flags: false,
		framework: "nodejs"
	};

	nexe.compile( options, ( err ) => {
		console.log( err );
		callback( err );
	} );
} );
```

**Comment by jaredallard** [comment]
Reproduced. Working on it right now!

**Comment by the-s0urce** [comment]
Same error here on Windows 10 and node.js v4.2.6

**Comment by jaredallard** [comment]
@the-s0urce What version of npm?

**Comment by the-s0urce** [comment]
npm 2.14.12

**Comment by jaredallard** [comment]
@the-s0urce Sorry, I'm tired, I meant what version of nexe?

**Comment by the-s0urce** [comment]
Nexe Version is **1.1.0**

Btw. here is the full error, just to be sure, its the same:
`D:\nodejs>nexe -i input_file.js -o output_file.exe
----> framework => nodejs
----> downloading https://nodejs.org/dist/node-latest.tar.gz
[====================================================================================================]
----> extracting the node source [node-tar.gz]
----> extraction finished
----> bundle D:\nodejs\input_file.js
----> found browserify in C:\Users\[User]\AppData\Roaming\npm\node_modules\nexe\node_modules\browserify\bin\cmd.js
Error: Cannot find module 'process' from 'D:\nodejs'
    at C:\[User]\AppData\Roaming\npm\node_modules\nexe\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
    at process (C:\[User]\AppData\Roaming\npm\node_modules\nexe\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\[User]\AppData\Roaming\npm\node_modules\nexe\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
    at load (C:\[User]\AppData\Roaming\npm\node_modules\nexe\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\[User]\AppData\Roaming\npm\node_modules\nexe\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\[User]\AppData\Roaming\npm\node_modules\nexe\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

....> ERROR: Browserify failed to launch`

**Comment by jaredallard** [comment]
Alright, that's unrelated to this issue. However, could you give me a copy of the code you're using? I actually just created a *maybe* fix for that, and that would be a great test case before push.

**Comment by the-s0urce** [comment]
It contains company internal stuff, gimme some time to create a clean version and I can send you a copy later. I am quite new here, can I send file direct to you?

**Comment by jaredallard** [comment]
@the-s0urce Fair enough! You can just copy and past any reproducing code into here using ``` markdown, or you can post it on dropbox and post a link here, or put it on a git repo, anything works!

**Comment by the-s0urce** [comment]
> var sys = require ('util'),
> url = require('url'),
> http = require('http'),
> qs = require('querystring'),
> fs=require('fs'),
> process=require('process'),
> js2xml = require("js2xmlparser")
> ;
> 
> var api = {
>   read: 'http://any/json/and/or/html/api/site',
>   create: 'http://any/json/and/or/html/api/site',
>   delete: 'http://any/json/and/or/html/api/site'
> };
> 
> var ID='';
> 
> 
> http.get(api.create, function(res) {
>   var bodyChunks = [];
>   res.on('data', function(chunk) {
> 	bodyChunks.push(chunk);
>   }).on('end', function() {
> 	ID = Buffer.concat(bodyChunks).toString('utf-8');
> 	var api_read=api.read.replace('[id]',ID);
> 	
> 	console.log('Created: ',ID);
> 	
> 	setInterval(function(){
> 		http.get(api_read, function(res) {
> 		  var bodyChunks = [];
> 		  res.on('data', function(chunk) {
> 			bodyChunks.push(chunk);
> 		  }).on('end', function() {
> 			var body = Buffer.concat(bodyChunks);
> 			try {
> 				var curr=JSON.parse(body);
> 				console.log(curr);
> 			}catch (e) {}
> 		  })
> 		});
> 	},1000);
>   })
> });
> 
> 
> process.stdin.resume();
> 
> function exitHandler(options, err) {
>     if (options.cleanup){
> 		var api_delete=api.delete.replace('[id]',ID);
> 		http.get(api_delete, function(res) {
> 		  var bodyChunks = [];
> 		  res.on('data', function(chunk) {
> 		  bodyChunks.push(chunk);
> 		  }).on('end', function() {
> 			var body = Buffer.concat(bodyChunks).toString('utf8');
> 			if(body=='<HTML><BODY><B>DONE</B></BODY></HTML>')
> 				console.log('Deleted: ',ID);
> 			else
> 				console.log('Failed to delete, try manual:\n',api_delete);
> 		    if (err) console.log(err.stack);
> 			if (options.exit) process.exit();
> 		  });
> 		});
> 	}else{
> 		if (err) console.log(err.stack);
> 		if (options.exit) process.exit();
> 	}
> }
> 
> //do something when app is closings
> process.on('exit', exitHandler.bind(null,{cleanup:true}));
> 
> //catches ctrl+c event
> process.on('SIGINT', exitHandler.bind(null, {cleanup:true,exit:true}));
> 
> //catches uncaught exceptions
> process.on('uncaughtException', exitHandler.bind(null, {exit:true}));

**Comment by jaredallard** [comment]
So, it works with master.

It produces this error now:

```js
Error: getaddrinfo ENOTFOUND any any:80
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

Not sure if that's from that snippet, but it compiles at least!

**Comment by the-s0urce** [comment]
Thank you for this really fix reaction, but I still get an error :/

```
----> framework => nodejs
----> embedResources undefined
----> resource -> D:\nodejs\tmp\nexe\nodejs\latest\node-v5.7.0\lib\nexeres.js
----> bundle D:\nodejs\prtg_debug_tracker.js
----> executing browserify via API
----> monkey patch D:\nodejs\tmp\nexe\nodejs\latest\node-v5.7.0\node.gyp
----> monkey patch D:\nodejs\tmp\nexe\nodejs\latest\node-v5.7.0\src\node.js
----> monkey patch D:\nodejs\tmp\nexe\nodejs\latest\node-v5.7.0\lib\child_process.js
----> vcbuild [make stage]
The command "python" could not be found.
Cannot determine current version of Node.js
....> ERROR: The release executable has not been generated. This indicates a failure in the build process. There is likely additional information above.
```

**Comment by jaredallard** [comment]
@the-s0urce So `python` isn't being found now. Have you tried making sure python is in %PATH% or manually specifiying it with `--python` or `nexe.python` (in `package.json`)
