### ISSUE TITLE
Source included in the binary

### ISSUE THREAD

**Issue by lionel590** [jaredallard/nexe#171]
Hi, I have just checked the compile binary and it seems that the source code is included on clear text. Is this the expected behavior ? 

Rgds

**Comment by jaredallard** [comment]
Hi! Do you mean that the source of your script is included in the binary? If so, that's normal. This is not meant to hide your source.

**Comment by jaredallard** [comment]
Closing as I'm sure you main it's visible in plain text, which isn't the aim of nexe.

**Comment by msolters** [comment]
Hi, to be clear, that source is necessary to be there for the resulting binary to work?  It seems that the purpose of this tool is to bundle a node binary with the source it will execute?

**Comment by jaredallard** [comment]
Yes it is at the moment. Though utilizing pre compiled "bytecode" may be
added sometime in order to compete with non free alternatives.

**Comment by msolters** [comment]
Ok thanks for the explicit confirmation

**Comment by rahul-dutt-sharma** [comment]
@jaredallard Can we think about adding obfuscation to the browserified code?

**Comment by jaredallard** [comment]
Hi, you could always minify it before building using gulp
Though hooks are planned in v2

On Fri, Oct 7, 2016, 9:39 AM rahul-dutt-sharma <notifications@github.com<mailto:notifications@github.com>> wrote:

@jaredallard<https://github.com/jaredallard> Can we think about adding obfuscation to the browserified code?

**Comment by rahul-dutt-sharma** [comment]
Minify my node project right ?Can you provide some trivial example please
