### ISSUE TITLE
Allow build windows exe under linux

### ISSUE THREAD

**Issue by biji** [jaredallard/nexe#174]
It would be great to build windows exe under linux

**Comment by jaredallard** [comment]
I believe this has been asked before, however this is impossible (to my knowledge). You'd need Visual Studio in order to do this and is really to much of a hassle. If there is a method of doing so for node, I could perhaps look into it, but until it won't be!

Thanks for the suggestion!

**Comment by TranceGeniK** [comment]
Maybe this is relevant : https://github.com/maxogden/electron-packager#building-windows-apps-from-non-windows-platforms
However I don't really know how it's done

**Comment by biji** [comment]
Thank you, tried that but resulting file is too big :dancer:
