### ISSUE TITLE
Error running GYP on Windows

### ISSUE THREAD

**Issue by reverentgeek** [jaredallard/nexe#175]
After updating to 1.0.8, running on Windows gives me the following error:

```
----> vcbuild [make stage]
Looking for Visual Studio 2015
Found Visual Studio 2015
configure  --dest-cpu=x86 --tag=
Error running GYP
gyp: deps\cares\cares.gyp not found (cwd: C:\_projects\leankit-data-utility-cli\tmp\nodejs\latest\node-v5.5.0) while loading dependencies of node.gyp while trying to load node.gyp
ctrpp not found in WinSDK path--using pre-gen files from tools/msvs/genfiles.
```

This is happening on both Windows 7 32-bit with Visual Studio 2013 installed, and Windows 10 64-bit with Visual Studio 2015 installed.

**Comment by jaredallard** [comment]
Hey, will check this out. I've been working primarily on Linux currently so Windows bugs are certainly possible. I've heard of issues with cares as of late, and it's odd that it keeps popping up as I cannot reproduce it on Linux (which is where it has come up before.) What node version exactly are you trying?

**Comment by reverentgeek** [comment]
I've got Node 5.5 installed on both VMs. Thanks!

**Comment by jaredallard** [comment]
Even stranger! My thought, currently, is that it has something to do with `node-tar.gz`, since some people said manually extracting it solved the problem. After testing node-tar.gz over native tar it is, infact, a node-tar.gz issue. Seems it doesn't follow symlinks, which node may be using for the deps.

**Comment by jaredallard** [comment]
Yea, for whatever reason it's failing to extract /deps/**/ contents

**Comment by jaredallard** [comment]
I've reported the issue to `node-tar.gz` here: https://github.com/alanhoff/node-tar.gz/issues/25

**Comment by jaredallard** [comment]
Let me know if it doesn't work for some reason!

**Comment by reverentgeek** [comment]
Seems to be working now. Thanks!

**Comment by jaredallard** [comment]
Awesome! Had to do a lot of new things, so I'm glad its all working well!
