### ISSUE TITLE
build-error

### ISSUE THREAD

**Issue by gbaumgart** [jaredallard/nexe#176]
Hi,
please add a check that the path is already absolute and exists before doing the path concat in:  https://github.com/jaredallard/nexe/blob/master/bin/nexe#L67

otherwise it will fail if you use it through grunt shell over networkshares. it somehow creates the cwd + abs path which fails

**Comment by jaredallard** [comment]
Honestly, I wonder if it's even needed as I use path.join for mostly everything anyways. Does `path.join`  do this automatically?

**Comment by jaredallard** [comment]
OHHH. Disregard that, I see what you're saying.

**Comment by jaredallard** [comment]
Sure! I'll implement this by tonight and most likely release it in 1.1.1

**Comment by gbaumgart** [comment]
and it only happens on windows...
ok, you close this.
thanks

**Comment by jaredallard** [comment]
I think this is fixed in master branch, let me know!

**Comment by gbaumgart** [comment]
thanks a lot, works!
