### ISSUE TITLE
Cannot find module error when building

### ISSUE THREAD

**Issue by kaithinkiq** [jaredallard/nexe#179]
I'm running into an error saying that a module cannot be found during the build process.

<img width="656" alt="screen shot 2016-02-05 at 6 40 36 pm" src="https://cloud.githubusercontent.com/assets/15836724/12864284/e21b8ab6-cc3a-11e5-86fc-29bef32410b6.png">

Nexe v1.1.0 is being run on Windows with the basic command
`nexe -i myapp.js -o myapp.exe`

The module that's causing the error is being required like so:
`module.exports.VariableIds        = require("lib/opcua_node_ids").VariableIds;`

It seems like the require path isn't being resolved correctly. After changing the require path to include `./` (` require("./lib/opcua_node_ids").VariableIds;`)this particular message disappears but other messages of the same type crop up.

**Comment by jaredallard** [comment]
I believe that apps need to refer to local paths as `./` so not sure if this is a design issue with browserify or not.

**Comment by jaredallard** [comment]
Yes, its trying to find the module `lib`, using ./ indicates its in the cwd not a npm module.

**Comment by kaithinkiq** [comment]
Ah ok. Thanks for the info.
