### ISSUE TITLE
Executable process first param as a node param

### ISSUE THREAD

**Issue by BrunoBonacci** [jaredallard/nexe#187]
Hi,

I'm using nexe to generate a cmd line tool but if I run `./myscript -h` or `myscript -v` the default node js help page or version are used rather than passing these parameters to my script.

Note that the script works correctly when executed as `node myscript.js -h`.
Another interesting observation is that this happens only for the first parameter,
if I execute `./myscript "" -h` (empty first parameter) then the arguments are forwarded to my script.

Is there any way to i can tell nexe to not process these arguments?

**Comment by jaredallard** [comment]
Yep! With nexe -F or nexe.runtime.ignoreFlags!

On February 22, 2016 4:50:11 AM PST, Bruno Bonacci <notifications@github.com> wrote:
>Hi,
>
>I'm using nexe to generate a cmd line tool but if I run `./myscript -h`
>or `myscript -v` the default node js help page or version are used
>rather than passing these parameters to my script.
>
>Note that the script works correctly when executed as `node myscript.js
>-h`.
>Another interesting observation is that this happens only for the first
>parameter,
>if I execute `./myscript "" -h` (empty first parameter) then the
>arguments are forwarded to my script.
>
>Is there any way to i can tell nexe to not process these arguments?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jaredallard/nexe/issues/187

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by BrunoBonacci** [comment]
Thanks @jaredallard, just for clarity it is the lowercase `-f`

```
nexe -f -i myscript.js -o myscript
```

**Comment by jaredallard** [comment]
Yea, sorry, bad sleep leads to messing them up! 

On February 22, 2016 8:32:35 AM PST, Bruno Bonacci <notifications@github.com> wrote:
>Thanks @jaredallard, just for clarity it is the lowercase `-f`
>
>```
>nexe -f -i myscript.js -o myscript
>``` 
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jaredallard/nexe/issues/187#issuecomment-187255350

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
