### ISSUE TITLE
Failed to find Visual Studio installation (with VS 2012)

### ISSUE THREAD

**Issue by nickich** [jaredallard/nexe#193]
It seems to look for Visual Studio 2013 or 2015 only and doesn't find my 2012. Is VS 2012 supported? The doc says VS 2010+. Any options I'm missing?
Part of the log:
----> vcbuild [make stage]
Looking for Visual Studio 2015
Looking for Visual Studio 2013
Failed to find Visual Studio installation.
....> ERROR: The release executable has not been generated. This indicates a fai
lure in the build process. There is likely additional information above.
Press any key to continue...

**Comment by ashking** [comment]
Facing the same issue. 

This probably needs README update on requirements too.

**Comment by nickich** [comment]
It's not a nexe issue. It looks like node.js discontinued the VS2012 support in 2014. The latest commit with VS2012 support is d22637c  on Oct 10, 2014. Looking at the node.js releases (https://nodejs.org/en/download/releases/) looks like the latest release supporting VS2012 is Node.js v0.11.14, so if you put in your nexe options "nodeVersion: '0.11.14'" it should work.
