### ISSUE TITLE
Is necessary to bundle node_modules into binary?

### ISSUE THREAD

**Issue by Kurtas** [jaredallard/nexe#197]
This is probably stupid question, but I would like to ask you if is possible to confiure a nexe to compile binary without including ```node_modules``` & ```config``` directory?

My app structure:
```
./node_modules
./config //directory with configuration -> db passwords, settings etc
app.js //Whole app already budled in 1 file using webpack
```

Now I would like make a binary from ```app.js``` and allow them use modules from ```config``` and ```node_modules``` directory

**Comment by jaredallard** [comment]
It does this automatically, to not bundle config, just don't require it.

node_modules isn't actually ever bundled per say.

**Comment by divmgl** [comment]
I don't understand. Does this mean an `npm install` is required regardless of `nexe`?
