### ISSUE TITLE
Ignore node_modules - no such native module

### ISSUE THREAD

**Issue by scramble45** [jaredallard/nexe#201]
I have an application that contains a large amount of required modules. I wish to compile the application and ignore all modules so they are not bundled into the standalone application but instead read outside of it. I have read through the documentation and perhaps I'm not understanding how to properly exclude things from nexe. 

I also noticed that nexe/browserify seems to have problems with optional dependencies such as fsevents. I had to comment out  quite a few "try" statements for loading these optional module dependencies. I honestly don't really mind keeping my modules outside my main application, do however care about have a way to protect my code. Any suggestions here would be great, here is a sample of my latest attempt at getting this working.

```
node.js:872
      throw new Error(`No such native module ${id}`);
      ^

Error: No such native module ./transports/Console
    at NativeModule.require (node.js:872:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at Object.Console (nexe.js:6753:16)
    at Object.__dirname.35../bragi/canLog (nexe.js:6366:23)
    at s (nexe.js:1:316)
    at nexe.js:1:367
    at Object.__dirname.1.bragi-node (nexe.js:9:13)
    at s (nexe.js:1:316)
    at e (nexe.js:1:487)
```

Another observation is that: using the nexe exclude for a specific module in package.json doesnt seem to be working for me. example below:

```
 "main": "app.js",
     "browser": {
          "chokidar": false
      },
      "nexe": {
          "browserify": {
              "excludes": ["chokidar", "fsevents"],
              "paths": ["/node_code"]
          }
      },
...
```

**Comment by jaredallard** [comment]
Hi! Any reproducing code so I can give you a project specific fix for now

**Comment by vovasapsay** [comment]
Hi! It's help for me.
`var mymodule = GLOBAL.require('./mymodule.node');`

**Comment by jaredallard** [comment]
This is an issue with browserify, with a fix posted above. Closing.

**Comment by soniagandhi** [comment]
GLOBAL.require is throwing error saying
"require is not a property in global"
Do I need to install any package for this?
