### ISSUE TITLE
Revert to non browserify system

### ISSUE THREAD

**Issue by jaredallard** [jaredallard/nexe#204]
Ever since I implemented browserify as our packing system we've had no end of problems. However, it does fix some problems. Here's a list of solutions I think may work to solve this: 

* Support both methods (I.e `package: browserify`) this also brings the ability to implemented other packaging methods down the road.
* Look into webpack more, which supports lazy loading.
* Just use the old method that had less issues, but more big lib issues.

Please, if you have an opinion, say it here! I'm more do in favor or the former option, but it'd be better to get input as this project is vastly depended on.

**Comment by Gawran** [comment]
Supporting various packaging methods sounds good to me. As you said, in the future there might be some better solutions or maybe that option will inspire somebody to develop one specifically for nexe.

**Comment by nevf** [comment]
I haven't used browserify so can't comment on it, however I am using ```jspm``` in fairly large & complex app it is is excellent.

**Comment by jaredallard** [comment]
@nevf Good to know, will try that as well! :tada:

**Comment by jaredallard** [comment]
This is in the mainlain of 2.0 "status"! Closing to remove duplication
