### ISSUE TITLE
Issue with non basic ascii characters

### ISSUE THREAD

**Issue by woverton** [jaredallard/nexe#206]
These characters are not displayed once compiled

```
─┬┌┐─┴└┘│├─┼│┤│█░▒▓
```

I have been unable to track down where this is happening. It looks like they are replaced with spaces during compilation.

Is it possible to pass in a flag to allow non basic ascii characters?

```
$ nexe --version
1.1.1
```

**Comment by woverton** [comment]
I notice you're using base64:
https://github.com/jaredallard/nexe/blob/da7b6af0faca3500888ffae7b9ac7e5603f00dff/lib/embed.js#L36

Could this be the issue: https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_.22Unicode_Problem.22

**Comment by woverton** [comment]
Nevermind, I replaced all references of base64 with utf8 and it makes no difference.

**Comment by jaredallard** [comment]
Hi this might be done in lib/bundle.js. I'll check it out :)

**Comment by woverton** [comment]
Did you get anywhere with this?

**Comment by jaredallard** [comment]
lib/bundle.js#118 may be the problem. Haven't tried yet.

**Comment by woverton** [comment]
I'll give it a go and get back to you

**Comment by woverton** [comment]
I've tried expanding the regex to fit up to 0xDF which would compile, but still did not show those characters

**Comment by jaredallard** [comment]
Hmm... interesting. Not sure why this is.

**Comment by Skuldur** [comment]
BUMP. This is still causing problems.

**Comment by jaredallard** [comment]
@Skuldur To be frank, I have no idea why this is an issue. It must have something to do with the core libs in Node.js being treated differently.

**Comment by jaredallard** [comment]
Well, unsure of why, but it seems to be working in the v2.0.0 branch (nowhere near production ready yet) w/ browserify.

**Comment by woverton** [comment]
This is still an issue :(
```
nexe --version
1.1.2
```

What is the eta on the v2 branch?

**Comment by foxever** [comment]
Maybe it caused by nodejs js2c.py please also check with your node version. I notice some characters been stripped when converting from nexe.js to a C array, you can compare bundled nexe.js with the final binary in hex editor to address the issue (nexe.js is OK, but binary is not).
ps. I notice in node 4.4.7, they remove the minify process in js2c.py, it may solve the issue, I guess

**Comment by jaredallard** [comment]
Yep, it's working fine in node 7 with nexe v2
