### ISSUE TITLE
nexe doesn't work on node 0.10

### ISSUE THREAD

**Issue by Leekao** [jaredallard/nexe#212]
test.js has 1 line and it's "console.log(1);".
`C:\projects\Nginx>nexe -i test.js -o test.exe `
returns:
```
C:\Users\User\AppData\Roaming\npm\node_modules\nexe\lib\exe.js:28
const async = require("async"),
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\nexe\lib\index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by jaredallard** [comment]
This looks like an older version, or I haven't published the version that fixes this. Can you try `master` branch and get back to me?

**Comment by Leekao** [comment]
I installed from npm if it helps

**Comment by brettlangdon** [comment]
I am seeing the same issue on `OSX`

```bash
$ node --version
v0.10.40
$ npm --version
1.4.28
$ npm list nexe
└── nexe@1.1.2
$ ./node_modules/.bin/nexe --help

/path/to/project/node_modules/nexe/lib/exe.js:28
const async = require("async"),
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

    at require (module.js:380:17)
    at Object.<anonymous> (/path/to/project/node_modules/nexe/lib/index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by Leekao** [comment]
Still not working, any news?

**Comment by jaredallard** [comment]
@Leekao What version of node are you using? Also, can you get a `head` output of around 30 lines of exe.js for me?

**Comment by Leekao** [comment]
tried 10.33, 10.40, failed on both, also tried cloning the repo and got same exact results.
I could give you a head output if you want but it's the exact same code seen on the repository so I don't know what use it will be.

**Comment by Leekao** [comment]
works perfect on node 5.2.

**Comment by jaredallard** [comment]
Sounds like an issue with node.js and ES6 then :/ may have to remove support for running nexe on 0.10

**Comment by brettlangdon** [comment]
@jaredallard it looks like the only ES6 features being used are `const` and `let`, if those were converted into `var` then this should work fine on older versions of node.

**Comment by jaredallard** [comment]
v2 Will be using more ES6 features including arrow funcs and more, so I'm marking this as wontfix. Node 0.10 is very old to begin with.

**Comment by brettlangdon** [comment]
`0.10.x` is still under LTS until October. Not that I expect that to change the state of this, but more as an FYI.

**Comment by jaredallard** [comment]
@brettlangdon Hmmm, does 0.10 support any sort of harmony flags?

**Comment by brettlangdon** [comment]
Yes, probably not exactly the features you want, but here are the harmony flags my version of node supports

```
         --harmony_typeof (enable harmony semantics for typeof)
               type: bool  default: false
         --harmony_scoping (enable harmony block scoping)
               type: bool  default: false
         --harmony_modules (enable harmony modules (implies block scoping))
               type: bool  default: false
         --harmony_proxies (enable harmony proxies)
               type: bool  default: false
         --harmony_collections (enable harmony collections (sets, maps, and weak maps))
               type: bool  default: false
         --harmony (enable all harmony features (except typeof))
               type: bool  default: false
```

**Comment by mikeblazek** [comment]
I know you marked this as wont fix.  But i'm on the latest version of Node and getting this same error.

**Comment by jaredallard** [comment]
@mikeblazek 6.x? 😲

**Comment by mikeblazek** [comment]
Sorry I didn't upgrade completely.  I'm on 6.x now.

**Comment by syarul** [comment]
what you can do is `npm i babel babel-preset-es2015` in the nexe installation folder then run `babel lib --out-dir lib --presets es2015`. You should be able to use it with legacy version of node.js afterwards.
