### ISSUE TITLE
Child_Process.fork Not Working?

### ISSUE THREAD

**Issue by medemi68** [jaredallard/nexe#215]
Hey Guys,

I'm trying to figure out how to use child_process.fork while using nexe.
How can I modify my script so that I can still use child_process.fork as it normally is.

I'd normally use child_process.spawn, but I need the ipc wrapper that comes with it.

**Comment by jaredallard** [comment]
Hi, it's highly likely that it's broken. node changes constanly and most other patches have had to be updated, however, I don't really use `child_process.fork` so if it did break I'd have a bit of a hard time fixing it.

**Comment by nightwolfz** [comment]
Yeah it just launches the executable that called child_process.fork again with different args.

**Comment by medemi68** [comment]
I managed to make a work around by bundling node with my exectuable, and then using
var child = spawn('./node', 'filename.js', {cwd: path.resolve("./"), stdio: [null, null, null, 'ipc']} );

**Comment by jaredallard** [comment]
Closing due to your work around :)

**Comment by medemi68** [comment]
Maybe add that to the documentation?

**Comment by rahul-dutt-sharma** [comment]
The above is not the same as fork right ?

**Comment by c9fe** [comment]
It's the same. Fork just spawns a node process to run your script.

Docs: https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options
