### ISSUE TITLE
Node/v8 compiles using only one core

### ISSUE THREAD

**Issue by rpelizzi** [jaredallard/nexe#220]
I didn't see a flag for this in your documentation, and both `npm config  set jobs N` and `export JOBS=N` seem to be ignored. Is there a way to use more cores to compile the static node binary?

**Comment by jaredallard** [comment]
Yeah, it should be one of the make flag options. Doesn't use npm's config
as its not through gyp.

**Comment by BruceBerry** [comment]
oh ok I see it now... it's just not supported in the binary.

**Comment by lapsio** [comment]
how to add such flag?

**Comment by BruceBerry** [comment]
I just patched it in in my local installation by editing `node_modules/nexe/bin/nexe` and adding `nodeMakeArgs: ["-j", "4"]` to the argument passed to `nexe.compile`.

If you want a more permanent solution, you can either a) make your own script that calls `nexe.compile` with the flag (`bin/nexe` is just a command line wrapper around it after all) or b) register the flag with the argument parser used in `bin/nexe` and then make a pull request :-)
