### ISSUE TITLE
Arguments to browserify

### ISSUE THREAD

**Issue by mdnasr** [jaredallard/nexe#222]
I want to add `--node` argument to browserify, Is there a way to do it. 

Another way is to run browserify in code by myself and make nexe stop calling browserify but i cannot find option to stop browserify. When browserify run second time in nexe it gives the follwing error:

    Error: Cannot find module './lib/get' from '/root/code'
        at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
        at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
        at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
        at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
        at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by jaredallard** [comment]
Hi, `--node` is implied with how we configure browserify right now.
