### ISSUE TITLE
Unable to find Visual Studio 2015

### ISSUE THREAD

**Issue by KraXarN** [jaredallard/nexe#227]
Trying to compile, but fails with
> ----> vcbuild [make stage]
> Looking for Visual Studio 2015
> Looking for Visual Studio 2013
> Failed to find Visual Studio installation.
> ....> ERROR: The release executable has not been generated. This indicates a failure in the build > process. There is likely additional information above.

Using nexe 1.1.2 on Windows 7 x64

**Comment by CKarper** [comment]
So, you need to get Visual Studio in order to build on Windows...
you can get the free / community edition.

**Comment by KraXarN** [comment]
It's installed under `C:\Program Files (x86)\Microsoft Visual Studio 14.0`

**Comment by KraXarN** [comment]
Removing the temp folder and running it again fixed it
