### ISSUE TITLE
Problem deploying with node_modules folder

### ISSUE THREAD

**Issue by anthonylai** [jaredallard/nexe#248]
Hi,

  I am new to nexe and maybe I just do not understand how it works.  All I want to do is have my code in binary.  I wish to keep all the nodejs libraries in the node_modules folder without compiling.  My code can compile but it throws an error while executing:

  This is my simple nodejs test js file (index-nexe.js):

```
'use strict';
const loadRequire = function(name) {
  return require(name);
};

const express = loadRequire('express');
console.log('helloworld');
```

This is the command I execute:

`nexe -i index-nexe.js -o cass0
`

I have the node_modules folder along side with the executable (cass0) with express.  I am using a mac.

When I execute ./cass0, it throws the following error:

```
 ./cass0
bootstrap_node.js:435
      throw new Error(`No such native module ${id}`);
      ^

Error: No such native module express
    at NativeModule.require (bootstrap_node.js:435:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at loadRequire (nexe.js:4:10)
    at Object.__dirname.1 (nexe.js:7:17)
    at s (nexe.js:1:316)
    at e (nexe.js:1:487)
    at nexe.js:1:505
    at NativeModule.compile (bootstrap_node.js:502:7)
    at Function.NativeModule.require (bootstrap_node.js:443:18)
```

Can you please kindly let me know what is the problem?  Your help is greatly appreciated.

Thanks.
Sincerely,
Anthony

**Comment by jaredallard** [comment]
Hi, as per the readme: "dynamic require calls do not work". Try just using require('express')

On Sun, Aug 28, 2016, 23:08 Anthony Lai <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

I am new to nexe and maybe I just do not understand how it works. All I want to do is have my code in binary. I wish to keep all the nodejs libraries in the node_modules folder without compiling. My code can compile but it throws an error while executing:

This is my simple nodejs test js file (index-nexe.js):

'use strict';
const loadRequire = function(name) {
  return require(name);
};

const express = loadRequire('express');
console.log('helloworld');


This is the command I execute:

nexe -i index-nexe.js -o cass0

I have the node_modules folder along side with the executable (cass0) with express. I am using a mac.

When I execute ./cass0, it throws the following error:

 ./cass0
bootstrap_node.js:435
      throw new Error(`No such native module ${id}`);
      ^

Error: No such native module express
    at NativeModule.require (bootstrap_node.js:435:13)
    at s (nexe.js:1:176)
    at nexe.js:1:367
    at loadRequire (nexe.js:4:10)
    at Object.__dirname.1 (nexe.js:7:17)
    at s (nexe.js:1:316)
    at e (nexe.js:1:487)
    at nexe.js:1:505
    at NativeModule.compile (bootstrap_node.js:502:7)
    at Function.NativeModule.require (bootstrap_node.js:443:18)


Can you please kindly let me know what is the problem? Your help is greatly appreciated.

Thanks.
Sincerely,
Anthony

**Comment by anthonylai** [comment]
Hi @jaredallard ,

  Thank you very much for your quick response.

  Yes, I specifically make it a dynamic require as I do not wish to include express into the binary itself.  How can I have express separately placed in a node_modules folder instead?  

  Thanks.
Sincerely,
Anthony

**Comment by jaredallard** [comment]
For now, just call global.require to use the native require function, and get out of the "sandbox".

On Sun, Aug 28, 2016, 23:48 Anthony Lai <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @jaredallard<https://github.com/jaredallard> ,

Thank you very much for your quick response.

Yes, I specifically make it a dynamic require as I do not wish to include express into the binary itself. How can I have express separately placed in a node_modules folder instead?

Thanks.
Sincerely,
Anthony

**Comment by anthonylai** [comment]
Hi @jaredallard,

  Got it!  Thank you for your quick response and great help.  nexe is amazing.  Really appreciate it.

  Thanks.
Sincerely,
Anthony
