### ISSUE TITLE
Cannot combine "code usage" options and "package.json" options, and they are not the same

### ISSUE THREAD

**Issue by cosmo0** [jaredallard/nexe#251]
I have a project for which I need to ignore libraries, so I ignore them through `package.json`.

```
{
  // snip

  "nexe": {
    "input": "./server.js",
    "output": "server^$",
    "browserify": {
        "requires": [],
        "excludes": [
          "some", "packages"
        ],
        "paths": []
    },
    "runtime": {
        "framework": "node",
        "version": "6.5.0"
    }
  }
}
```

Now, my build server may not have python installed, so I want to specify a custom python path.

* I tried to add a `python` section to the `packages.json` file but it doesn't seems to be working.
* I tried `nexe -p "tmp\python\"` but it doesn't find python.exe and seems to ignore the parameter.
* I also tried to create a `build.js` file :

```
var nexe = require('nexe');

nexe.compile({
    input: 'server.js',
    output: 'server^$',
    nodeVersion: '6.5.0',
    nodeTempDir: 'tmp',
    python: 'tmp/python/',
    resourceFiles: [ ],
    resourceRoot: [ ],
    flags: true,
    jsFlags: "--use_strict",
    framework: "node"
}, function(err) {
    if(err) {
        return console.log(err);
    }
});
```

but calling `node build.js` seems to ignore the excluded packages section.

How can I both specify a custom python path and excluded packages ?

**Comment by JoseExposito** [comment]
What version of Nexe are you using? I'm running 1.1.2:

```
$ nexe --version
1.1.2
```

And I can confirm that the Python option works. Detailed explanation:

This is my package.json file:

```
"nexe": {
    "input": "bin/www",
    "output": "APP",
    "temp": "nexe_tmp",
    "python": "/python/path",
    "debug": false,
    "browserify": {
        "requires": [],
        "excludes": [
          "some", "packages"
        ],
        "paths": []
    },
    "runtime": {
      "framework": "node",
      "version": "6.4.0",
      "ignoreFlags": true
    }
  }
```

When I run Nexe I get:

```
$ nexe
----> input => 'bin/www'
----> output => 'APP'
----> temp => 'nexe_tmp'
----> python => '/python/path'
----> debug => 'false'
----> set python as /python/path
----> framework => node
----> embedResources undefined
```

As you can see it detects my python path. The options specified in package.json have preference over the ones specified as command line arguments. For example, if you try to run it this way, you will notice it ignores the command line "-p" option:

```
$ nexe -p /command/line/python/path
----> input => 'bin/www'
----> output => 'APP'
----> temp => 'nexe_tmp'
----> python => '/python/path'
----> debug => 'false'
----> set python as /python/path
----> framework => node
----> embedResources undefined
```

But, if you remove the Python section from the package.json:

```
$ nexe -p /command/line/python/path
----> input => 'bin/www'
----> output => 'APP'
----> temp => 'nexe_tmp'
----> debug => 'false'
----> set python as /command/line/python/path
----> framework => node
----> embedResources undefined
```

**Comment by cosmo0** [comment]
Yep, turns out I was just using Python3... thanks :smile:
