### ISSUE TITLE
Failed to find Visual Studio 2015

### ISSUE THREAD

**Issue by alexandre1985** [jaredallard/nexe#265]
I'm on a windows 10 x64 machine.
I have all the requirements installed, including Visual Studio (2015).
My script has one line and is  `console.log('hello');`
When I try to compile it with `nexe` it gives me this error:

`----> vcbuild [make stage]
Looking for Visual Studio 2015
Failed to find Visual Studio installation.
....> ERROR: The release executable has not been generated. This indicates a fai                                              lure in the build process. There is likely additional information above.`

What should I do?

**Comment by alexandre1985** [comment]
It also gives me this error above
`----> executing browserify via API
....> WARNING: src/node.js doesn't exist. Trying 'lib/internal/bootstrap_node.js'`

**Comment by rahul-dutt-sharma** [comment]
@alexandre1985 this is normal for nexe. 

`----> executing browserify via API ....> WARNING: src/node.js doesn't exist. Trying 'lib/internal/bootstrap_node.js'`

**Comment by rahul-dutt-sharma** [comment]
Have you tried installing the node-gyp build system https://github.com/nodejs/node-gyp#installation

**Comment by alexandre1985** [comment]
With `node-gyp` I tried in Linux and it compile, thanks. In Windows I haven't tried yet; when I get home I will try it.
If `node-gyp` is required, it should be on the "Requirements" on the project page, for us (beginners) to know

**Comment by rahul-dutt-sharma** [comment]
I would hop in and make a PR for the readme file. That being said there is always google and one will eventually end up learning more from the errors as compared to straight forward step a->z directions present in readme. I ended up learning a ton of stuff from this repos' lack of holistic readme 😜

**Comment by alexandre1985** [comment]
I have tried in Windows 10 and I still get the first error that I reported. It can find Visual Studio installation.
I have Microsoft Visual Studio Community 2015 and my path is:
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe"

**Comment by alexandre1985** [comment]
When installing Visual Studio you have to make sure you install C++ support (by default it doesn't).
This should be on README too. Or else people might skip your project and try another way

**Comment by rahul-dutt-sharma** [comment]
@alexandre1985 Hi I was about to send the C++ tooling installation miss last night but then I fell asleep :)
I would like to give a small input here. Most people would figure that out from the readme that since we are going to download node source code and use VCbuildArgs from the node projects vcbuild.bat file we would need to be able to build node. The link in code example leads us to the vcbuild.bat file in node github page which then makes everything clear. I hope to make a PR about what all I needed to figure out that should be present in readme file. That way it would be all good :)

**Comment by alexandre1985** [comment]
Thank you @rahul-dutt-sharma for everything
