### ISSUE TITLE
package.json error

### ISSUE THREAD

**Issue by alexandre1985** [jaredallard/nexe#266]
Hi. I'm trying to build an binary that has `var xray = require('x-ray');` in the node script.
It is giving me some errors so in trying to do what the README tells me to.
I'm on point [Browserify Require Issues](https://github.com/jaredallard/nexe#browserify-require-issues) but is giving me some errors. This is what I did:
I tried to create a package.json and then I executed `nexe` on the command line. It shows me this error:

> module.js:590
    throw err;
    ^
SyntaxError: C:\Users\danny\dev\MeusProgramas\horoscopo\package.json: Unexpected token : in JSON at position 6
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.exports.package (C:\Users\danny\AppData\Roaming\npm\node_modules\nexe\lib\exe.js:962:16)
    at Object.<anonymous> (C:\Users\danny\AppData\Roaming\npm\node_modules\nexe\bin\nexe:84:22)
    at Module._compile (module.js:570:32)

This is my `package.json`:
```
"nexe": {
    "input": "horos.js",
    "output": "horos^$",
    "temp": "src",
    "browserify": {
        "requires": [],
        "excludes": [],
        "paths": []
    },
    "runtime": {
        "framework": "node",
        "version": "6.9.0",
        "js-flags": "--use_strict",
        "ignoreFlags": true
    }
}
```

What should I do?

**Comment by anmonteiro** [comment]
By the error message it looks like you have a typo in your `package.json`

**Comment by alexandre1985** [comment]
But I have copied the json from the README example as you can see

**Comment by anmonteiro** [comment]
if that's the whole contents of your `package.json` you need to add braces around it. e.g.:
```json
{
"nexe": {
...
}
}
```

**Comment by alexandre1985** [comment]
Of course. I'm really a beginner :)
Obrigado @anmonteiro

**Comment by alexandre1985** [comment]
It can be made more explicit in the README for beginners like me to don't fall under this issue

**Comment by alexandre1985** [comment]
Now I'm trying add `x-ray` module, and I'm trying to do what is in  [Browserify Require Issues](https://github.com/jaredallard/nexe#browserify-require-issues).
Should my `package.json` be like this?
```
{
    "nexe": {
        "input": "horos.js",
        "output": "horos^$",
        "temp": "src",
        "browserify": {
            "requires": [
                {
                    "file": "horos.js",
                    "expose": "x-ray"
                },
                "x-ray.js"
            ],
            "excludes": [],
            "paths": []
        },
        "runtime": {
            "framework": "node",
            "version": "latest",
            "js-flags": "--use_strict",
            "ignoreFlags": true
        }
    }
}
```
