### ISSUE TITLE
Not compiling .js with require a non-native module

### ISSUE THREAD

**Issue by alexandre1985** [jaredallard/nexe#267]
My node program (horos.js) is not compiling. It has a `var xray = require('x-ray');` in it, and I have installed `x-ray` (https://github.com/lapwinglabs/x-ray) throw `npm install x-ray` on my project directory.
I have tried both in `nexe@0.4.2` and I have tried with package.json being as in the 2 examples of [Browserify Require Issues](https://github.com/jaredallard/nexe#browserify-require-issues).
Still not working.
This is the error that I have got when I run the command `nexe` on my project directory:
```
$ nexe
----> input => 'horos.js'
----> output => 'node.exe'
----> temp => 'src'
----> framework => node
----> embedResources undefined
----> resource -> C:\Users\danny\dev\MeusProgramas\horoscopo\src\node\4.6.1\node-v4.6.1\lib\nexeres.js
----> bundle horos.js
----> executing browserify via API
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'emitter' from 'C:\Users\danny\dev\MeusProgramas\horoscopo\node_modules\x-ray\node_modules\batch'
    at C:\Users\danny\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\danny\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\danny\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\danny\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\danny\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\danny\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```
my `package.json` is:
```
{
    "nexe": {
        "input": "horos.js",
        "output": "node^$",
        "temp": "src",
        "browserify": {
            "requires": [],
            "excludes": [],
            "paths": []
        },
        "runtime": {
            "framework": "node",
            "version": "4.6.1",
            "js-flags": "--use_strict",
            "ignoreFlags": true
        }
    }
}
```
What should I do?
Thank you

**Comment by jaredallard** [comment]
Try manually installing emitter, OR try browserify.excludes

On Fri, Oct 21, 2016, 2:42 PM Daniel Alexandre Cerqueira Santos <notifications@github.com<mailto:notifications@github.com>> wrote:

My node program (horos.js) is not compiling. It has a var xray = require('x-ray'); in it, and I have installed x-ray throw npm install x-ray on my project directory.
I have tried both in nexe@0.4.2 and I have tried with package.json being as in the 2 examples of Browserify Require Issues.
Still not working.
This is the error that I have got when I run the command nexe on my project directory:

$ nexe
----> input => 'horos.js'
----> output => 'node.exe'
----> temp => 'src'
----> framework => node
----> embedResources undefined
----> resource -> C:\Users\danny\dev\MeusProgramas\horoscopo\src\node\4.6.1\node-v4.6.1\lib\nexeres.js
----> bundle horos.js
----> executing browserify via API
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'emitter' from 'C:\Users\danny\dev\MeusProgramas\horoscopo\node_modules\x-ray\node_modules\batch'
    at C:\Users\danny\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\danny\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\danny\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\danny\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\danny\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\danny\AppData\Roaming\npm\node_modules\nexe\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)


my package.json is:

{
    "nexe": {
        "input": "horos.js",
        "output": "node^$",
        "temp": "src",
        "browserify": {
            "requires": [],
            "excludes": [],
            "paths": []
        },
        "runtime": {
            "framework": "node",
            "version": "4.6.1",
            "js-flags": "--use_strict",
            "ignoreFlags": true
        }
    }
}


What should I do?
Thank you

**Comment by alexandre1985** [comment]
Thank you @jaredallard . I did install emitter and I also have installed entities and it did work!
I'm so happy! =)
Thank you so much for this tool

**Comment by jaredallard** [comment]
@alexandre1985 Also, I'd make sure you run it somewhere *without* `node_modules` as you never know if it's only working because of it's presence there. (the compiled binary). Cheers!

**Comment by alexandre1985** [comment]
I tested that. It's working ;)
Thank You
