### ISSUE TITLE
project dead?

### ISSUE THREAD

**Issue by gbaumgart** [jaredallard/nexe#276]
hi,
there are a number of unsolved issues, and pull requests are just ignored. 

is it better to go on with an own fork ? 

thanks !

**Comment by CKarper** [comment]
Not dead, just stuck in molasses.

I'll try to review the PRs this week.  Hopefully I'll have some time with the holiday.

**Comment by gbaumgart** [comment]
right on, thanks a lot !

**Comment by jaredallard** [comment]
It's not dead, just really tough to work this into my busy life right now (work, school, teaching, writing software for the class I teach).

PRs are sorta stale as I'm trying to manage how to introduce them into v2 so nothing gets accidentally dropped. A lot of the issues are the same issue; the single file methods aren't near perfect. Some work well, some don't work well, this has been a problem for a long time and likely will be for a while.
